spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  application:
    name: community-service


server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,beans,refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

